apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::066971257572:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-5zMMJWrtPUoi
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:bootstrappers
      - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::066971257572:user/suresh
      username: suresh
      groups:
      - roboshop-trainee
    - userarn: arn:aws:iam::066971257572:user/ramesh
      username: ramesh
      groups:
      - roboshop-admin
