apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::066971257572:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-5zMMJWrtPUoi
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::111122223333:user/admin
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-16T05:51:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1150"
  uid: 444462c5-11c5-4bef-afc2-359d11e506a8