apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin
rules:
- apiGroups: ["*"] #indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: roboshop-cluster-reader
rules:
- apiGroups: [""] #indicates the core API group
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["storage.k8s.io"] #indicates the core API group
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list"]