apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::066971257572:role/eksctl-roboshop-addon-iamserviceaccount-robos-Role1-aqcmQbVFBGkm
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop-secret-reader
  namespace: roboshop

